config/routes.rb
ResumeApp::Application.routes.draw do
  get "errors/error_404"

  get "errors/error_500"

  resources :tags
  resources :users
  resources :resumes
  resources :sessions, :only => [:new, :create, :destroy]
  resources :static_pages
  resources :password_resets
  resources :activities
  resources :awards
  resources :education
  resources :positions
  resources :experiences, :only => [:new, :edit, :create, :update, :destroy]
  resources :skills
  resources :styles
  resources :beta_requests
  resources :beta_codes, :only => [:index, :new, :edit, :create, :update, :destroy]

  root to: 'static_pages#index'
  match '/sitemap', to: 'sitemaps#show'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match 'users/:id/password', to: 'users#password', :as => "edit_password"
  match 'users/:id/make_admin', to: 'users#make_admin', :as => "make_admin"
  match 'users/:id/revoke_admin', to: 'users#revoke_admin', :as => "revoke_admin"
  match 'users/:id/linkedin', to: 'users#linkedin', :as => "linkedin_user"
  match 'users/:id/import', to: 'users#import', :as => "linkedin_user_import", :via => :put
  match '/request_invite', to: 'beta_requests#new', :as => "request_invite"
  match 'password_resets/:id/admin_password_reset', to: 'password_resets#admin_password_reset', :as => "admin_password_reset"

  match '/auth/:provider/callback', to: 'authorizations#create', :as => "authorization"
  match '/activities/:id/linkedin', to: 'activities#linkedin', :as => "linkedin_activities"
  match '/activities/:id/import', to: 'activities#import', :as => "linkedin_activities_import"
  match '/awards/:id/linkedin', to: 'awards#linkedin', :as => "linkedin_awards"
  match '/awards/:id/import', to: 'awards#import', :as => "linkedin_awards_import"
  match '/education/:id/linkedin', to: 'education#linkedin', :as => "linkedin_education"
  match '/education/:id/import', to: 'education#import', :as => "linkedin_education_import"
  match '/positions/:id/linkedin', to: 'positions#linkedin', :as => "linkedin_positions"
  match '/positions/:id/import', to: 'positions#import', :as => "linkedin_positions_import"
  match '/skills/:id/linkedin', to: 'skills#linkedin', :as => "linkedin_skills"
  match '/skills/:id/import', to: 'skills#import', :as => "linkedin_skills_import"

  match 'resumes/:id/export', to: 'resumes#export', :as => "export_resume"
  match 'resumes/:id/analyze', to: 'resumes#analyze', :as => "analyze_resume"
  match 'resumes/:id/map', to: 'resumes#map', :as => "map_resume"
  match 'resumes/:id/get_map_data', to: 'resumes#get_map_data', :as => "get_map_data"
  match 'styles/:id/set_base_style', to: 'styles#set_base_style', :as => "set_base_style", :via => :post

  match 'experiences/mass_add', to: 'experiences#mass_add', :as => "experience_mass_add"
  match 'experiences/mass_create', to: 'experiences#mass_create', :as => "experience_mass_create", :via => :post

  match 'master_resumes/', to: 'master_resumes#index', :as => "master_resumes"
  match 'master_resumes/edit', to: 'master_resumes#edit', :as => "edit_master_resumes"
  match 'master_resumes/new', to: 'master_resumes#new', :as => "new_master_resumes"

  match '/features', to: 'static_pages#features', :as => "features"
  match '/about', to: 'static_pages#about', :as => "about"
  match '/contact', to: 'static_pages#contact', :as => "contact"
  match 'static_pages/contact_form', to: 'static_pages#contact_form'
  match '/privacy_policy', to: 'static_pages#privacy_policy', :as => "privacy"
  match '/terms_of_service', to: 'static_pages#terms_of_service', :as => "terms"

    match '*not_found', to: 'errors#error_404'

end

app/models/style.rb
# == Schema Information
#
# Table name: styles
#
#  id          :integer         not null, primary key
#  description :string(255)
#  filename    :string(255)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Style < ActiveRecord::Base
	attr_accessible :base_style, :description, :print_filename, :screen_filename

	has_attached_file :screen_filename, 
#					  :url => "/system/:class/:attachment/:id/:style/:basename.:extension",
#					  :path => ":rails_root/public/system/:class/:attachment/:id/:style/:basename.:extension"
					  :url => "/resume_styles/:basename.:extension",
					  :path => ":rails_root/public/resume_styles/:basename.:extension"


	has_attached_file :print_filename,
					  :url => "/resume_styles/:basename.:extension",
					  :path => ":rails_root/public/resume_styles/:basename.:extension"
	has_many :resumes

# Validations
	validates_attachment_presence :print_filename
	validates_attachment_content_type :print_filename, :content_type => ['text/css', 'application/css-stylesheet', 'text/scss']

	validates_attachment_presence :screen_filename
	validates_attachment_content_type :screen_filename, :content_type => ['text/css', 'application/css-stylesheet', 'text/scss']

	before_destroy :destroy_style


	def self.create_styles_array
		dropdown = Array.new

		styles = Style.all

		styles.each do |s|
			css = [s.description, s.id]
			dropdown << css
		end

		return dropdown
	end

	def self.set_base_style(style_id)
		base = Style.find(style_id)

		Style.update_all({:base_style => 0}, {:id => Style.all})

		base.base_style = 1
		base.save
	end

	private
    	def destroy_style
    		if Style.count <= 1 
      			errors.add(:base, 'Cannot destroy the last style!')
      			return false
      		end
    	end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
	before_filter :signed_in_user

	def index
		@styles = Style.all

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @styles }
		end
	end

	def show
		@style = Style.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @style }
		end
	end

	def new
		@style = Style.new

		respond_to do |format|
		  format.html # new.html.erb
		  format.json { render json: @style }
		end
	end

	def edit
		@style = Style.find(params[:id])
	end

	def create
		@style = Style.new(params[:style])

		respond_to do |format|
			if @style.save
				flash[:success] = 'Style was successfully created.'
				format.html { redirect_to styles_url }
				format.json { render json: @style, status: :created, location: @style }
			else
				format.html { render action: "new" }
				format.json { render json: @style.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		@style = Style.find(params[:id])

		respond_to do |format|
			if @style.update_attributes(params[:style])
				flash[:success] = 'Style was successfully updated.'
				format.html { redirect_to styles_url }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @style.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@style = Style.find(params[:id])

		base = Style.find_by_base_style(1)
		if Resume.update_all({:style_id => base.id}, {:id => Resume.find_all_by_style_id(params[:id])})
			if @style.base_style == 1 
				flash[:error] = 'Can\'t delete base style! Please choose another base before deleting.'
			elsif @style.destroy
				flash[:success] = 'Style deleted.'
			else 
				flash[:error] = 'Can\'t delete last style!'
			end
		else 
			flash[:error] = 'Unable to update resumes with base style!'
		end

		respond_to do |format|
			format.html { redirect_to styles_url }
			format.json { head :no_content }
		end
	end

	def set_base_style
		@style = Style.set_base_style(params[:id])

		respond_to do |format|
			if @style
				flash[:success] = 'Base style set'
				format.html { redirect_to styles_url }
				format.json { head :no_content }
			else 
				flash[:error] = 'There was a problem setting the base style!'
				format.html { redirect_to styles_url }
				format.json { head :no_content }
			end
		end
	end

end

app/views/styles/_form.html.erb
<%= form_for(@style, :html => { :multipart => true }) do |f| %>
    <% if @style.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h2>

            <ul>
                <% @style.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="row">
        <div class="span4">
            <div class="field">
                <%= f.label :description %><br />
                <%= f.text_field :description %>
            </div>
            <div class="field">
                <%= f.label :screen_filename %><br />
                <%= f.file_field :screen_filename %>
            </div>
            <div class="field">
                <%= f.label :print_filename %><br />
                <%= f.file_field :print_filename %>
            </div>
        </div>
    </div>
    <div class="row">
        <%= f.submit "Save", :class => 'btn-large btn-primary' %>
        <%= link_to "Cancel", styles_url %>
    </div>
<% end %>

app/views/styles/edit.html.erb
<% provide(:title, "Edit Your Style") %>
<h1>Edit Style</h1>
<%= render 'form' %>

app/views/styles/index.html.erb
<% provide(:title, "Styles") %>

<h1>Styles</h1>
<p>(Bold indicates base style)</p>
<br />
	<div class="row">
		<div class="span3">
			<strong>Style Name</strong>
		</div>
		<div class="span2">
			<strong>Screen Filename</strong>
		</div>
		<div class="span2">
			<strong>Print Filename</strong>
		</div>
	</div>
	<% @styles.each do |style| %>
		<% if style.base_style == 1 %>
			<div class="row base-style">
		<% else %>
			<div class="row">
		<% end %>
			<div class="span3">
				<%= link_to style.description, style_path(style.id) %>
			</div>
			<div class="span2">
				<p><%= File.basename(style.screen_filename_file_name) %></p>
			</div>
			<div class="span2">
				<p><%= File.basename(style.print_filename_file_name) %></p>
			</div>
			<div class="span4 offset1">
			<p><%= link_to edit_style_path(style) do %> 
						<i class="icon-search icon-edit"></i> Edit
					<% end %>
					| 
					<%= link_to style, confirm: 'Are you sure?', method: :delete do %>
						<i class="icon-search icon-trash"></i> Delete
					<% end %>
					|
					<%= link_to "Set As Base", set_base_style_path(style.id), method: :post %>
				</p>
			</div>
		</div>
	<% end %>

<%= link_to 'New Style', new_style_path, :class => "btn" %>

app/views/styles/new.html.erb
<% provide(:title, "Create A New Style") %>

<h1>Create New Style</h1>
<%= render 'form' %>