config/routes.rb
ResumeApp::Application.routes.draw do
  get "errors/error_404"

  get "errors/error_500"

  resources :tags
  resources :users
  resources :resumes
  resources :sessions, :only => [:new, :create, :destroy]
  resources :static_pages
  resources :password_resets
  resources :activities
  resources :awards
  resources :education
  resources :positions
  resources :experiences, :only => [:new, :edit, :create, :update, :destroy]
  resources :skills
  resources :styles
  resources :beta_requests
  resources :beta_codes, :only => [:index, :new, :edit, :create, :update, :destroy]

  root to: 'static_pages#index'
  match '/sitemap', to: 'sitemaps#show'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match 'users/:id/password', to: 'users#password', :as => "edit_password"
  match 'users/:id/make_admin', to: 'users#make_admin', :as => "make_admin"
  match 'users/:id/revoke_admin', to: 'users#revoke_admin', :as => "revoke_admin"
  match 'users/:id/linkedin', to: 'users#linkedin', :as => "linkedin_user"
  match 'users/:id/import', to: 'users#import', :as => "linkedin_user_import", :via => :put
  match '/request_invite', to: 'beta_requests#new', :as => "request_invite"
  match 'password_resets/:id/admin_password_reset', to: 'password_resets#admin_password_reset', :as => "admin_password_reset"

  match '/auth/:provider/callback', to: 'authorizations#create', :as => "authorization"
  match '/activities/:id/linkedin', to: 'activities#linkedin', :as => "linkedin_activities"
  match '/activities/:id/import', to: 'activities#import', :as => "linkedin_activities_import"
  match '/awards/:id/linkedin', to: 'awards#linkedin', :as => "linkedin_awards"
  match '/awards/:id/import', to: 'awards#import', :as => "linkedin_awards_import"
  match '/education/:id/linkedin', to: 'education#linkedin', :as => "linkedin_education"
  match '/education/:id/import', to: 'education#import', :as => "linkedin_education_import"
  match '/positions/:id/linkedin', to: 'positions#linkedin', :as => "linkedin_positions"
  match '/positions/:id/import', to: 'positions#import', :as => "linkedin_positions_import"
  match '/skills/:id/linkedin', to: 'skills#linkedin', :as => "linkedin_skills"
  match '/skills/:id/import', to: 'skills#import', :as => "linkedin_skills_import"

  match 'resumes/:id/export', to: 'resumes#export', :as => "export_resume"
  match 'resumes/:id/analyze', to: 'resumes#analyze', :as => "analyze_resume"
  match 'resumes/:id/map', to: 'resumes#map', :as => "map_resume"
  match 'resumes/:id/get_map_data', to: 'resumes#get_map_data', :as => "get_map_data"
  match 'styles/:id/set_base_style', to: 'styles#set_base_style', :as => "set_base_style", :via => :post

  match 'experiences/mass_add', to: 'experiences#mass_add', :as => "experience_mass_add"
  match 'experiences/mass_create', to: 'experiences#mass_create', :as => "experience_mass_create", :via => :post

  match 'master_resumes/', to: 'master_resumes#index', :as => "master_resumes"
  match 'master_resumes/edit', to: 'master_resumes#edit', :as => "edit_master_resumes"
  match 'master_resumes/new', to: 'master_resumes#new', :as => "new_master_resumes"

  match '/features', to: 'static_pages#features', :as => "features"
  match '/about', to: 'static_pages#about', :as => "about"
  match '/contact', to: 'static_pages#contact', :as => "contact"
  match 'static_pages/contact_form', to: 'static_pages#contact_form'
  match '/privacy_policy', to: 'static_pages#privacy_policy', :as => "privacy"
  match '/terms_of_service', to: 'static_pages#terms_of_service', :as => "terms"

    match '*not_found', to: 'errors#error_404'

end

app/models/award.rb
# == Schema Information
#
# Table name: awards
#
#  id          :integer         not null, primary key
#  user_id     :integer
#  description :string(255)
#  date        :date
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Award < ActiveRecord::Base
  	attr_accessible :date, :description, :user_id, :tag_ids, :skill_ids, :skill_tokens, :tag_tokens
  	attr_reader :skill_tokens, :tag_tokens

# Associations
	has_and_belongs_to_many :tags
	has_and_belongs_to_many :skills
  	belongs_to :user

# Validations
	validates :date, :presence => true, :date => { :before => Time.now }
	validates :user_id, :presence => true
	validates :description, :presence => true

# Methods
	def skill_tokens=(tokens)
#        self.skill_ids = Skill.ids_from_tokens(tokens)
    end

    def tag_tokens=(tokens)
    end
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
	include ApplicationHelper

	before_filter :signed_in_user
	
	def index
		@awards = current_user.awards.order("date DESC")

		respond_to do |format|
			format.html
			format.json { render json: @awards }
		end
	end

	def show
		respond_to do |format|
			format.html { redirect_to master_resumes_url }
		end
	end

	def new
		@award = Award.new
		@tags = current_user.tags
		@skills = current_user.skills

		respond_to do |format|
			format.html
			format.json { render json: @award }
		end
	end

	def create
		@award = current_user.awards.new(params[:award])
		@award.tag_ids = parse_tags(params[:award][:tag_tokens], 'Tag')
		@award.skill_ids = parse_tags(params[:award][:skill_tokens], 'Skill')

		respond_to do |format|
			if @award.save
				flash[:success] = "Award was successfully created!"
				format.html { redirect_to master_resumes_url }
				format.json { render json: @award, status: :created, location: @award }
			else 
				flash.now[:error] = "There was an error saving your Award"
				format.html { render action: "new" }
				format.json { render json: @award, status: :unprocessable_entity }
			end
		end
	end

	def linkedin
	    @user = User.find(current_user)

	    client = LinkedIn::Client.new("twcsgivs3zzd", "LaxvcuYD59XwZhxL")

		if @user.linkedin_atoken.nil?
			flash[:error] = "It does not appear you have connected your LinkedIn account"
			redirect_to(@user)
		elsif client.authorize_from_access(@user.linkedin_atoken, @user.linkedin_secret)
			linkedin = client.profile(:fields => %w(honors))
#raise linkedin.to_yaml
#raise linkedin.honors.split(/[\n]/).to_yaml
			@awards = Array.new
			if !linkedin.honors.nil?
				honors = linkedin.honors.split(/[\n]/)
				regex = /([0-9]{1,2}[\-.\/])?([0-9]{1,2}[\-.\/])?([0-9]{2,4})/
				
				honors.each do |item|
					description = item.split(regex)
					@awards.push(description[0])
				end
			end
			@current = current_user.award.all

			@search_array = []
			@current.each do |name|
				@search_array << name.description
			end

			respond_to do |format|
				format.html
			end
		else
			flash[:error] = "There was a problem authenticating your LinkedIn account.  Please retry connecting it."
			redirect_to(current_user)
		end
	end

	def import
		error = 0

		params[:import].each do |honor|
			new_award = current_user.award.create(:description => honor, :date => Date.today)

			if new_award.save!
				error += 0
			else 
				error += 1
			end
		end

		if error = 0
			flash[:success] = "Awards were imported successfully"
			redirect_to(current_user)
		else
			flash[:error] = "Your awards may not have fully loaded"
			respond_to do |format|
				format.html { render action: "linkedin" }
			end
		end
	end

	def edit
		@award = Award.find(params[:id])
		@tags = current_user.tags
		@skills = current_user.skills
	end

	def update
		@award = Award.find(params[:id])
		params[:award][:tag_ids] ||= []
		params[:award][:skill_ids] ||= []

		params[:award][:tag_ids] = parse_tags(params[:award][:tag_tokens], 'Tag')
		params[:award][:skill_ids] = parse_tags(params[:award][:skill_tokens], 'Skill')

		respond_to do |format|
		  if @award.update_attributes(params[:award])
		  	flash[:success] = "Award was successfully created!"
			format.html { redirect_to master_resumes_url }
			format.json { head :no_content }
		  else
			format.html { render action: "edit" }
			format.json { render json: @award.errors, status: :unprocessable_entity }
		  end
		end
  	end

	def destroy
		@award = Award.find(params[:id])
		@award.destroy

		respond_to do |format|
			flash[:notice] = "Award deleted"
			format.html { redirect_to master_resumes_url }
			format.json { head :no_content }
		end
	end
end

app/views/awards/_form.html.erb
<%= form_for(@award) do |f| %>
    <% if @award.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@award.errors.count, "error") %> prohibited this award from being saved:</h2>

            <ul>
                <% @award.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="item-form">
        <div class="description">
            <%= f.label :description %><br />
            <%= f.text_field :description %>
        </div>
        <div class="item-dates">
            <div class="field">
                <%= f.label :date %><br />
                <%= f.date_select :date, :start_year => 1980 %>
            </div>
        </div>
    </div>
    <div class="item-tags">
        <h3><i class="icon-plus icon-white"></i>Choose Tags</h3>
        <div class="tag-field">
            <%= f.text_field :tag_tokens, data: { load: @award.tags } %>
        </div>
    </div>
    <div class="item-skills">
        <h3><i class="icon-plus icon-white"></i>Choose Skills</h3>
        <div class="skill-field">
            <%= f.text_field :skill_tokens, data: { load: @award.skills } %>
        </div>
    </div>
    <div class="item-buttons">
        <%= f.submit "Save", :class => 'btn-large btn-primary' %>
        <%= link_to "Cancel", master_resumes_url %>
    </div>
<% end %>

app/views/awards/_linkedin_form.html.erb
<div class="linkedin-form">
	<% if @awards.count == 0 %>
		<div class="row import-header">
			<h4>You do not have any awards on your LinkedIn account!</h4>
		</div>
	<% else %>
		<%= form_tag("/awards/#{@user.id}/import") do %>
			<div class="row">
				<div class="row import-header">
					<div class="span1">
						<h4>Import</h4>
					</div>
					<div class="span4">
						<h4>Description</h4>
					</div>
					<div class="span3">
						<h4>Currently In Your Resume</h4>
					</div>
				</div>
				<div class="row import-content">
					<div class="span5 import-form">
						<% @awards.each do |option| %>
							<div class="row option">
								<div class="span1 checkbox">
									<%= check_box_tag('import[]', option) %>
								</div>
							</div>
							<div class="span4 description">
								<%= option %>
							</div>
						</div>
					<% end %>
				</div>
				<div class="span3 current-items">
					<ul>
						<% @current.each do |skill| %>
							<li><%= skill.organization %></li>
						<% end %>
					</ul>
				</div>
			</div>
			<div class="row import-buttons">
				<%= hidden_field_tag("user_id", @user.id) %>
				<%= submit_tag "Save", :class => 'btn-large btn-primary' %>
				<%= link_to "Cancel", @user, :class => 'btn btn-large', :style => "margin: 0 0 0 0;" %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/awards/_master_awards.html.erb
<a id="awards">
<div class="master-section">
	<div class="master-section-header">
		<h2>Awards</h2>
		<%= link_to "Add New Award", new_award_path, :class=> "add-new btn btn-small pull-right" %>
	</div>
	<% if @awards.nil? %>
		<div class="line-item">
			<h4>You have no awards entered!  <%= link_to "Add One Now", new_award_path %></h4>
		</div>
	<% else %>
		<% @awards.each do |award| %>
			<div class="line-item-award<% if award.tags.count == 0 %> no-tag<% end %>">
				<div class="description">
					<h4><%= award.description %> (<%= display_date(award.date) %>)</h4>
					<% if award.tags.count > 0 %>
						<div class="tag-list">
							<ul>
								<i class="icon-search icon-tag"></i>
								<% award.tags.each do |t| %>
									<%= render 'tags/master_tag_list', :t => t %>
								<% end %>
							</ul>
						</div>
					<% end %>
				</div>
				<div class="actions">
					<ul>
						<li><%= link_to edit_award_path(award) do %>
								<i class="icon-search icon-edit"></i>
							<% end %>
						</li>
						<li><%= link_to edit_award_path(award) do %>
								<i class="icon-search icon-tag"></i>
							<% end %>
						</li>
						<li><%= link_to award_path(award), confirm: 'Are you sure?', method: :delete do %>
								<i class="icon-search icon-trash"></i>
							<% end %>
						</li>
					</ul>
				</div>
			</div>
		<% end %>
	<% end %>
</div>

app/views/awards/edit.html.erb
<% provide(:title, "Edit Your Award") %>
<h1>Edit Award</h1>
<%= render 'form' %>

app/views/awards/index.html.erb
<% provide(:title, "#{current_user.first_name}'s Awards") %>

<h1>Awards</h1>
<ul>
	<% @awards.each do |award| %>
		<li><%= link_to award.description, award_path(award.id) %></li>
	<% end %>
</ul>

app/views/awards/linkedin.html.erb
<% provide(:title, "Import Awards") %>
<div class="row">     
    <div class="span12">
		<p id="notice"><%= notice %></p>
	</div>
</div>

<div class="row">
	<%= render 'users/sidebar' %>
	<div class="span9 offset1 linkedin-import">
		<div class="row linkedin-instructions">
			<h1>Import Awards From LinkedIn</h1>
        	<p>Please note that due to the way that LinkedIn handles Honors and Awards, you will need to input the appropriate dates after you have imported your awards.</p>
		</div>
		<%= render 'linkedin_form' %>
	</div>
</div>

app/views/awards/new.html.erb
<% provide(:title, "Create A New Award") %>

<h1>Create New Award</h1>
<%= render 'form' %>