config/routes.rb
ResumeApp::Application.routes.draw do
  get "errors/error_404"

  get "errors/error_500"

  resources :tags
  resources :users
  resources :resumes
  resources :sessions, :only => [:new, :create, :destroy]
  resources :static_pages
  resources :password_resets
  resources :activities
  resources :awards
  resources :education
  resources :positions
  resources :experiences, :only => [:new, :edit, :create, :update, :destroy]
  resources :skills
  resources :styles
  resources :beta_requests
  resources :beta_codes, :only => [:index, :new, :edit, :create, :update, :destroy]

  root to: 'static_pages#index'
  match '/sitemap', to: 'sitemaps#show'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match 'users/:id/password', to: 'users#password', :as => "edit_password"
  match 'users/:id/make_admin', to: 'users#make_admin', :as => "make_admin"
  match 'users/:id/revoke_admin', to: 'users#revoke_admin', :as => "revoke_admin"
  match 'users/:id/linkedin', to: 'users#linkedin', :as => "linkedin_user"
  match 'users/:id/import', to: 'users#import', :as => "linkedin_user_import", :via => :put
  match '/request_invite', to: 'beta_requests#new', :as => "request_invite"
  match 'password_resets/:id/admin_password_reset', to: 'password_resets#admin_password_reset', :as => "admin_password_reset"

  match '/auth/:provider/callback', to: 'authorizations#create', :as => "authorization"
  match '/activities/:id/linkedin', to: 'activities#linkedin', :as => "linkedin_activities"
  match '/activities/:id/import', to: 'activities#import', :as => "linkedin_activities_import"
  match '/awards/:id/linkedin', to: 'awards#linkedin', :as => "linkedin_awards"
  match '/awards/:id/import', to: 'awards#import', :as => "linkedin_awards_import"
  match '/education/:id/linkedin', to: 'education#linkedin', :as => "linkedin_education"
  match '/education/:id/import', to: 'education#import', :as => "linkedin_education_import"
  match '/positions/:id/linkedin', to: 'positions#linkedin', :as => "linkedin_positions"
  match '/positions/:id/import', to: 'positions#import', :as => "linkedin_positions_import"
  match '/skills/:id/linkedin', to: 'skills#linkedin', :as => "linkedin_skills"
  match '/skills/:id/import', to: 'skills#import', :as => "linkedin_skills_import"

  match 'resumes/:id/export', to: 'resumes#export', :as => "export_resume"
  match 'resumes/:id/analyze', to: 'resumes#analyze', :as => "analyze_resume"
  match 'resumes/:id/map', to: 'resumes#map', :as => "map_resume"
  match 'resumes/:id/get_map_data', to: 'resumes#get_map_data', :as => "get_map_data"
  match 'styles/:id/set_base_style', to: 'styles#set_base_style', :as => "set_base_style", :via => :post

  match 'experiences/mass_add', to: 'experiences#mass_add', :as => "experience_mass_add"
  match 'experiences/mass_create', to: 'experiences#mass_create', :as => "experience_mass_create", :via => :post

  match 'master_resumes/', to: 'master_resumes#index', :as => "master_resumes"
  match 'master_resumes/edit', to: 'master_resumes#edit', :as => "edit_master_resumes"
  match 'master_resumes/new', to: 'master_resumes#new', :as => "new_master_resumes"

  match '/features', to: 'static_pages#features', :as => "features"
  match '/about', to: 'static_pages#about', :as => "about"
  match '/contact', to: 'static_pages#contact', :as => "contact"
  match 'static_pages/contact_form', to: 'static_pages#contact_form'
  match '/privacy_policy', to: 'static_pages#privacy_policy', :as => "privacy"
  match '/terms_of_service', to: 'static_pages#terms_of_service', :as => "terms"

    match '*not_found', to: 'errors#error_404'

end

app/models/experience.rb
# == Schema Information
#
# Table name: experiences
#
#  id          :integer         not null, primary key
#  user_id     :integer
#  position_id :integer
#  description :string(255)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Experience < ActiveRecord::Base
  	attr_accessible :description, :position_id, :tag_ids, :skill_ids, :skill_tokens, :tag_tokens
    attr_reader :skill_tokens, :tag_tokens

# Associations
#	has_and_belongs_to_many :tags
  	belongs_to :position

  	has_and_belongs_to_many :tags
  	has_and_belongs_to_many :skills

# Validations
	validates :description, :presence => true
	validates :position_id, :presence => true

# scope :by_tag, lambda do |tag|
#    	joins(:experiences_tags).where('experiences_tags.tag_id = ?', tag) unless tag.nil?
#  	end

	def self.by_tag(tag_id)
		joins(:tags).where("tag_id = #{tag_id}")
	end


  def skill_tokens=(tokens)
#   self.skill_ids = Skill.ids_from_tokens(tokens)
  end

  def tag_tokens=(tokens)
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
	include ApplicationHelper
	
	before_filter :signed_in_user
	
	def index
	end

	def show
		@position = Position.build_position_by_position_id(params[:id])

		respond_to do |format|
			format.html
			format.json { render json: @position }
		end
	end

	def new
		pos = current_user.positions.find(params[:pos])
		@position_id = pos.id.to_i
		@experience = pos.experiences.new
		@tags = current_user.tags
		@skills = current_user.skills

		respond_to do |format|
			format.html
			format.json { render json: @experience }
		end
	end

	def mass_add
		pos = current_user.positions.find(params[:pos])
		@position_id = pos.id.to_i

		respond_to do |format|
			format.html
		end
	end

	def create
		@position = Position.find(params[:experience][:position_id])
		@experience = @position.experiences.new(params[:experience])

		@experience.tag_ids = parse_tags(params[:experience][:tag_tokens], 'Tag')
		@experience.skill_ids = parse_tags(params[:experience][:skill_tokens], 'Skill')

		respond_to do |format|
			if @experience.save
				flash[:success] = "Experience was successfully created!"
				format.html { redirect_to master_resumes_url }
				format.json { render json: @experience, status: :created, location: @experience }
			else 
				flash[:error] = "There was an error saving your experience"
				format.html { render action: "new" }
				format.json { render json: @experience, status: :unprocessable_entity }
			end
		end
	end

	def mass_create
		error = 0
		# Grab the form elements
		position = Position.find(params[:position_id])
		list = params[:experience]

		# Loop through the form element and add the experiences to the database
		individual_exp = list.split("\r\n")
		individual_exp.each do |exp|
			experience_item = Experience.new
			experience_item.position_id = position.id
			experience_item.description = exp
			if experience_item.save
				error += 0
			else 
				error += 1
			end
		end

		# Notify the user of success or failure
		respond_to do |format|
			if error == 0
				flash[:success] = "All your experience was successfully created!"
				format.html { redirect_to master_resumes_url }
			else 
				flash[:error] = "There was an error inputting #{error} or more of your experiences"
				format.html { render action: "mass_new" }
			end
		end
	end

	def edit
		@experience = Experience.find(params[:id])
		@position_id = @experience.position_id
		@tags = current_user.tags
		@skills = current_user.skills
	end

	def update
		position = Position.find(params[:experience][:position_id])
		@experience = position.experiences.find(params[:id])

		params[:experience][:tag_ids] ||= []
		params[:experience][:skill_ids] ||= []

		params[:experience][:tag_ids] = parse_tags(params[:experience][:tag_tokens], 'Tag')
		params[:experience][:skill_ids] = parse_tags(params[:experience][:skill_tokens], 'Skill')

		respond_to do |format|
			if @experience.update_attributes(params[:experience])
				flash[:success] = "Experience was successfully updated!"
				format.html { redirect_to master_resumes_url }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @position.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@experience = Experience.find(params[:id])
		@experience.destroy
		
		respond_to do |format|
			format.html { redirect_to master_resumes_url }
			format.json { head :no_content }
		end
	end
end

app/views/experiences/_form.html.erb
<%= form_for(@experience) do |f| %>
    <% if @experience.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

            <ul>
                <% @experience.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="item-form">
        <%= f.hidden_field :position_id, :value => @position_id %>
        <div class="description">
            <%= f.text_field :description, :placeholder => "Description" %>
        </div>
    </div>
    <div class="item-tags">
        <h3><i class="icon-plus icon-white"></i>Choose Tags</h3>
        <div class="tag-field">
            <%= f.text_field :tag_tokens, data: { load: @experience.tags } %>
        </div>
    </div>

    <div class="item-skills">
        <h3><i class="icon-plus icon-white"></i>Choose Skills</h3>
        <div class="skill-field">
            <%= f.text_field :skill_tokens, data: { load: @experience.skills } %>
        </div>
    </div>
    <div class="item-buttons">
        <%= f.submit "Save", :class => 'btn-large btn-primary' %>
        <%= link_to "Cancel", master_resumes_url %>
    </div>
<% end %>

app/views/experiences/_mass_form.html.erb
<%= form_tag '/experiences/mass_create', :method => :post do %>
    <div class="row experience-form">
        <div class="span7">
            <%= hidden_field_tag :position_id, @position_id %>
            <div class="field">
                <%= text_area_tag 'experience', nil, :cols => "50", :rows => "15" %>
            </div>
        </div>
        <div class="span5">
            <h3>Create your experience for this position all at once!</h3>
            <p>Add all your experience into the text area.  Make sure you put each experience
                on a new line to have them created correctly.</p>
        </div>
    </div>
    <div class="row">
        <%= submit_tag "Save", :class => 'btn-large btn-primary' %>
        <%= link_to "Cancel", master_resumes_url %>
    </div>
<% end %>

app/views/experiences/_master_experience_detail.html.erb
<% if job[:experience].count == 0 %>
	<div class="experience-item">
		<div class="experience-description">
			<p>You have no experience entered!  
				<%= link_to "Add Some Now", new_experience_path({ :pos => job[:position].id })%>
			</p>
		</div>
	</div>
<% else %>
	<% job[:experience].each do |exp| %>
		<div class="experience-item<% if exp.tags.count == 0 %> no-tag<% end %>">
			<div class="experience-description">
				<p><%= exp.description %></p>
				<% if exp.tags.count > 0 %>
					<div class="tag-list">
						<ul>
							<i class="icon-search icon-tag"></i>
							<% exp.tags.each do |t| %>
								<%= render 'tags/master_tag_list', :t => t %>
							<% end %>
						</ul>
					</div>
				<% end %>
			</div>
			<div class="actions">
				<ul>
					<li><%= link_to edit_experience_path(exp.id) do %>
							<i class="icon-search icon-edit"></i>
						<% end %>
					</li>
					<li><%= link_to edit_experience_path(exp) do %>
							<i class="icon-search icon-tag"></i>
						<% end %>
					</li>
					<li><%= link_to experience_path(exp), confirm: 'Are you sure?' 	, method: :delete do %>
							<i class="icon-search icon-trash"></i>
						<% end %>
					</li>
				</ul>
			</div>
		</div>
	<% end %>
<% end %>

app/views/experiences/_master_experiences.html.erb
<div class="row new-section">
	<h3 class="section-header">Positions</h3>
	<p class="add-new"><%= link_to "(Add New Position)", new_position_path %></p>
	<br />
	<% if @positions.nil? %>
		<div class="row line-item">
			<p>You have no positions entered!  <%= link_to "Add One Now", new_position_path %></p>
		</div>
	<% else %>
	<% @positions.each do |job| %>
		<div class="row line-item">
			<h4><%= job[:position].company %> - <%= job[:position].title %>, 
			<%= job[:position].city %>, <%= job[:position].state %>
			(<%= display_date(job[:position].start_date) %> - 
				<% if job[:position].start_date == job[:position].end_date || 
					  job[:position].end_date == Date.today %>
					Current
				<% else %>
					<%= display_date(job[:position].end_date) %>
				<% end %>
				)</h4>
			<p class="add-new">(
				<%= link_to "Edit", edit_position_path(job[:position].id) %> | 
				<%= link_to "Delete", position_path(job[:position].id), 
					confirm: 'Are you sure?', method: :delete %>)
			</p>
			<ul>
				<% job[:experience].each do |exp| %>
					<div class="row">
						<div class="span6">
							<li><%= exp.description %></li>
						</div>
						<div class="span2">
							<ul class="actions">
								<li><%= link_to "Edit", edit_experience_path(exp.id) %></li>
								<li><%= link_to "Tag", edit_experience_path(exp) %></li>
								<li><%= link_to "Delete", experience_path(exp), 
									confirm: 'Are you sure?', method: :delete %></li>
							</ul>
						</div>
					</div>
				<% end %>
				<div class="row">
					<%= link_to "Add Experience", new_experience_path({ :pos => job[:position].id }) %> | 
					<%= link_to "Add Multiple Experiences", experience_mass_add_path({ :pos => job[:position].id }) %>
				</div>
			</ul>
		</div>
	<% end %>	


<% end %>
</div>

app/views/experiences/edit.html.erb
<% provide(:title, "Edit An Experience") %>

<h1>Edit Experience for <%= @experience.position.company %></h1>
<%= render 'form' %>

app/views/experiences/index.html.erb
<h1>Experience#index</h1>
<p>Find me in app/views/experiences/index.html.erb</p>

app/views/experiences/mass_add.html.erb
<% provide(:title, "Create A New Experiences") %>

<h1>Create New Experiences</h1>
<%= render 'mass_form' %>

app/views/experiences/new.html.erb
<% provide(:title, "Create A New Experience") %>

<h1>Create New Experience for <%= @experience.position.company %></h1>
<%= link_to "I want to add a bunch of experiences at once...", experience_mass_add_path({ :pos => params[:pos] }) %>
<%= render 'form' %>