config/routes.rb
ResumeApp::Application.routes.draw do
  get "errors/error_404"

  get "errors/error_500"

  resources :tags
  resources :users
  resources :resumes
  resources :sessions, :only => [:new, :create, :destroy]
  resources :static_pages
  resources :password_resets
  resources :activities
  resources :awards
  resources :education
  resources :positions
  resources :experiences, :only => [:new, :edit, :create, :update, :destroy]
  resources :skills
  resources :styles
  resources :beta_requests
  resources :beta_codes, :only => [:index, :new, :edit, :create, :update, :destroy]

  root to: 'static_pages#index'
  match '/sitemap', to: 'sitemaps#show'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match 'users/:id/password', to: 'users#password', :as => "edit_password"
  match 'users/:id/make_admin', to: 'users#make_admin', :as => "make_admin"
  match 'users/:id/revoke_admin', to: 'users#revoke_admin', :as => "revoke_admin"
  match 'users/:id/linkedin', to: 'users#linkedin', :as => "linkedin_user"
  match 'users/:id/import', to: 'users#import', :as => "linkedin_user_import", :via => :put
  match '/request_invite', to: 'beta_requests#new', :as => "request_invite"
  match 'password_resets/:id/admin_password_reset', to: 'password_resets#admin_password_reset', :as => "admin_password_reset"

  match '/auth/:provider/callback', to: 'authorizations#create', :as => "authorization"
  match '/activities/:id/linkedin', to: 'activities#linkedin', :as => "linkedin_activities"
  match '/activities/:id/import', to: 'activities#import', :as => "linkedin_activities_import"
  match '/awards/:id/linkedin', to: 'awards#linkedin', :as => "linkedin_awards"
  match '/awards/:id/import', to: 'awards#import', :as => "linkedin_awards_import"
  match '/education/:id/linkedin', to: 'education#linkedin', :as => "linkedin_education"
  match '/education/:id/import', to: 'education#import', :as => "linkedin_education_import"
  match '/positions/:id/linkedin', to: 'positions#linkedin', :as => "linkedin_positions"
  match '/positions/:id/import', to: 'positions#import', :as => "linkedin_positions_import"
  match '/skills/:id/linkedin', to: 'skills#linkedin', :as => "linkedin_skills"
  match '/skills/:id/import', to: 'skills#import', :as => "linkedin_skills_import"

  match 'resumes/:id/export', to: 'resumes#export', :as => "export_resume"
  match 'resumes/:id/analyze', to: 'resumes#analyze', :as => "analyze_resume"
  match 'resumes/:id/map', to: 'resumes#map', :as => "map_resume"
  match 'resumes/:id/get_map_data', to: 'resumes#get_map_data', :as => "get_map_data"
  match 'styles/:id/set_base_style', to: 'styles#set_base_style', :as => "set_base_style", :via => :post

  match 'experiences/mass_add', to: 'experiences#mass_add', :as => "experience_mass_add"
  match 'experiences/mass_create', to: 'experiences#mass_create', :as => "experience_mass_create", :via => :post

  match 'master_resumes/', to: 'master_resumes#index', :as => "master_resumes"
  match 'master_resumes/edit', to: 'master_resumes#edit', :as => "edit_master_resumes"
  match 'master_resumes/new', to: 'master_resumes#new', :as => "new_master_resumes"

  match '/features', to: 'static_pages#features', :as => "features"
  match '/about', to: 'static_pages#about', :as => "about"
  match '/contact', to: 'static_pages#contact', :as => "contact"
  match 'static_pages/contact_form', to: 'static_pages#contact_form'
  match '/privacy_policy', to: 'static_pages#privacy_policy', :as => "privacy"
  match '/terms_of_service', to: 'static_pages#terms_of_service', :as => "terms"

    match '*not_found', to: 'errors#error_404'

end

app/models/beta_request.rb
class BetaRequest < ActiveRecord::Base
  attr_accessible :email, :beta_code_id, :approved_at

  belongs_to :beta_codes

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

end

app/controllers/beta_requests_controller.rb
class BetaRequestsController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :admin_user, only: [:index, :edit, :update, :destroy]

  def index
    @beta_requests = BetaRequest.order("created_at ASC").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beta_requests }
    end
  end

  def new
    @beta_request = BetaRequest.new

    respond_to do |format|
      format.html { render :layout => "public" }# new.html.erb
      format.json { render json: @beta_request }
    end
  end

  def edit
    @beta_request = BetaRequest.find(params[:id])
    @beta_codes = BetaCode.create_codes_array  
  end

  def create
    @beta_request = BetaRequest.new(params[:beta_request])

    respond_to do |format|
      if @beta_request.save
        BetaRequestMailer.welcome_email(@beta_request).deliver

        format.html { redirect_to request_invite_url, notice: 'Beta request was successfully created.' }
        format.json { render json: @beta_request, status: :created, location: @beta_request }
      else
        format.html { render action: "new" }
        format.json { render json: @beta_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @beta_request = BetaRequest.find(params[:id])
    beta_code = BetaCode.find(params[:beta_request][:beta_code_id]).code
    @beta_request.approved_at = Time.now
    email = BetaRequest.find(params[:id]).email

    respond_to do |format|
      if @beta_request.update_attributes(params[:beta_request])
        BetaRequestMailer.approve_request_email(email, beta_code).deliver

        format.html { redirect_to beta_requests_url, notice: 'Beta request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beta_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @beta_request = BetaRequest.find(params[:id])
    @beta_request.destroy

    respond_to do |format|
      format.html { redirect_to beta_requests_url }
      format.json { head :no_content }
    end
  end
end

app/views/beta_requests/_form.html.erb
<%= form_for(@beta_request) do |f| %>
  <% if @beta_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beta_request.errors.count, "error") %> prohibited this beta_request from being saved:</h2>

      <ul>
      <% @beta_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="request-form">
 <div class="row">
        <div class="span4">
            <div class="field">
                <%= @beta_request.email %>
            </div>
        </div>
        <div class="span4">
            <div class="field">
              <%= select(:beta_request, :beta_code_id, @beta_codes) %>
            </div>
            <p><%= link_to "Create A New Beta Code", new_beta_code_path %></p>
        </div>
    </div>

    <div class="row">
        <%= f.submit "Save", :class => 'btn-large btn-primary' %>
        <%= link_to "Cancel", beta_requests_path %>
    </div>
<% end %>

app/views/beta_requests/edit.html.erb
<h1>Editing beta_request</h1>

<%= render 'form' %>

app/views/beta_requests/index.html.erb
<h1>Beta Requests</h1>
<br />
	<div class="row">
		<div class="span4">
			<strong>Email</strong>
		</div>
		<div class="span2">
			<strong>Created</strong>
		</div>
		<div class="span2">
			<strong>Approved</strong>
		</div>
	</div>
	<% @beta_requests.each do |request| %>
		<div class="row">
			<div class="span4">
				<%= request.email %>
			</div>
			<div class="span2">
				<p><%= display_date(request.created_at, "%m/%d/%Y") %></p>
			</div>
			<div class="span2">
				<p><%= display_date(request.approved_at, "%m/%d/%Y") %></p>
			</div>
			<div class="span4">
				<p><%= link_to "Approve", edit_beta_request_path(request) %> 
					|
					<%= link_to request, confirm: 'Are you sure?', method: :delete do %>
						<i class="icon-search icon-trash"></i> Delete
					<% end %>
				</p>
			</div>
		</div>
	<% end %>

<%= link_to 'New Beta Request', request_invite_path, :class => "btn" %>

app/views/beta_requests/new.html.erb
<% provide(:title, "Request Beta Invite") %>

<div class="invite-content">
	<div class="form-box">
		<h1>Request An Invite</h1>
		<div class="form-copy">
			<p>My Master Resume is currently in beta and testing to make sure we didn't 
				leave a sponge inside the programming.  Currently access is limited but you can request an invite and we'll send you one soon!</p>

			
			<%= form_for @beta_request, :method => :post do |f| %>
				<%= f.text_field :email, :placeholder => "Email" %>
				<%= submit_tag "Submit", :class=>"invite-button" %>
			<% end %>
			<%= link_to "Already have an invite code?  Sign up!", signup_path %>
		</div>
	</div>
</div>

app/views/beta_requests/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_beta_request_path(@beta_request) %> |
<%= link_to 'Back', beta_requests_path %>